name: front
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0
  http: ^0.13.4
  flutter_secure_storage: ^4.2.1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imgs/hermes.png
    - imgs/userImage1.jpeg
    - assets/icons/.
    - assets/imgs/.
  fonts:
    - family: ZenKurenaido
      fonts:
        - asset: fonts/ZenKurenaido-Regular.ttf
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-VariableFont_wght.ttf
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf